# -------------------------------
# MongoDB Deployment & Service
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30007
  selector:
    app: mongodb

# -------------------------------
# Backend Deployment & Service
# -------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftapp
  template:
    metadata:
      labels:
        app: giftapp
    spec:
      containers:
      - name: giftapp-container
        image: us.icr.io/sn-labs-krishornung/giftapp:latest
        ports:
        - containerPort: 3060
        env:
          - name: MONGO_URL
            value: "mongodb://mongodb-service:27017"
          - name: JWT_SECRET
            value: "mysecret"
      imagePullSecrets:
      - name: icr
---
apiVersion: v1
kind: Service
metadata:
  name: giftapp-service
spec:
  type: NodePort
  ports:
  - port: 3060
    targetPort: 3060
    nodePort: 30006
  selector:
    app: giftapp

# -------------------------------
# Frontend Deployment & Service
# -------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftwebsite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftwebsite
  template:
    metadata:
      labels:
        app: giftwebsite
    spec:
      containers:
      - name: giftwebsite-container
        image: us.icr.io/sn-labs-krishornung/giftwebsite:latest
        ports:
        - containerPort: 9000
      imagePullSecrets:
      - name: icr
---
apiVersion: v1
kind: Service
metadata:
  name: giftwebsite-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9000
    nodePort: 30005
  selector:
    app: giftwebsite
